// Auto-generated by `supabase gen types typescript`
// This file will be regenerated once Supabase is initialized.
// For now, it provides the minimal shape needed for type-safe clients.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: "rep" | "manager";
          team_id: string | null;
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: "rep" | "manager";
          team_id?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: "rep" | "manager";
          team_id?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          name: string;
          manager_id: string | null;
          included_reps: number;
          included_rep_price_cents: number;
          extra_rep_price_cents: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          manager_id?: string | null;
          included_reps?: number;
          included_rep_price_cents?: number;
          extra_rep_price_cents?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          manager_id?: string | null;
          included_reps?: number;
          included_rep_price_cents?: number;
          extra_rep_price_cents?: number;
          updated_at?: string;
        };
      };
      calls: {
        Row: {
          id: string;
          rep_id: string;
          team_id: string;
          audio_storage_path: string;
          duration_seconds: number;
          status: string;
          error_message: string | null;
          customer_name: string | null;
          customer_address: string | null;
          recorded_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          rep_id: string;
          team_id: string;
          audio_storage_path: string;
          duration_seconds?: number;
          status?: string;
          error_message?: string | null;
          customer_name?: string | null;
          customer_address?: string | null;
          recorded_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          audio_storage_path?: string;
          duration_seconds?: number;
          status?: string;
          error_message?: string | null;
          customer_name?: string | null;
          customer_address?: string | null;
          updated_at?: string;
        };
      };
      transcripts: {
        Row: {
          id: string;
          call_id: string;
          full_text: string;
          utterances: Json;
          language_code: string;
          deepgram_request_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          call_id: string;
          full_text: string;
          utterances?: Json;
          language_code?: string;
          deepgram_request_id?: string | null;
          created_at?: string;
        };
        Update: {
          full_text?: string;
          utterances?: Json;
          language_code?: string;
          deepgram_request_id?: string | null;
        };
      };
      call_analyses: {
        Row: {
          id: string;
          call_id: string;
          overall_score: number;
          overall_grade: string;
          summary: string;
          strengths: Json;
          improvements: Json;
          talk_ratio_rep: number;
          talk_ratio_customer: number;
          model_id: string;
          prompt_version: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          call_id: string;
          overall_score: number;
          overall_grade: string;
          summary: string;
          strengths?: Json;
          improvements?: Json;
          talk_ratio_rep?: number;
          talk_ratio_customer?: number;
          model_id?: string;
          prompt_version?: string;
          created_at?: string;
        };
        Update: {
          overall_score?: number;
          overall_grade?: string;
          summary?: string;
          strengths?: Json;
          improvements?: Json;
          talk_ratio_rep?: number;
          talk_ratio_customer?: number;
        };
      };
      call_sections: {
        Row: {
          id: string;
          call_id: string;
          analysis_id: string;
          section_type: string;
          start_ms: number;
          end_ms: number;
          summary: string;
          grade: string;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          call_id: string;
          analysis_id: string;
          section_type: string;
          start_ms: number;
          end_ms: number;
          summary: string;
          grade: string;
          order_index: number;
          created_at?: string;
        };
        Update: {
          section_type?: string;
          start_ms?: number;
          end_ms?: number;
          summary?: string;
          grade?: string;
          order_index?: number;
        };
      };
      objections: {
        Row: {
          id: string;
          call_id: string;
          analysis_id: string;
          start_ms: number;
          end_ms: number;
          utterance_text: string;
          category: string;
          rep_response: string;
          handling_grade: string;
          suggestion: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          call_id: string;
          analysis_id: string;
          start_ms: number;
          end_ms: number;
          utterance_text: string;
          category: string;
          rep_response: string;
          handling_grade: string;
          suggestion: string;
          created_at?: string;
        };
        Update: {
          category?: string;
          rep_response?: string;
          handling_grade?: string;
          suggestion?: string;
        };
      };
      coaching_notes: {
        Row: {
          id: string;
          call_id: string;
          author_id: string;
          timestamp_ms: number | null;
          content: string;
          audio_url: string | null;
          audio_duration_seconds: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          call_id: string;
          author_id: string;
          timestamp_ms?: number | null;
          content: string;
          audio_url?: string | null;
          audio_duration_seconds?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          content?: string;
          timestamp_ms?: number | null;
          audio_url?: string | null;
          audio_duration_seconds?: number | null;
          updated_at?: string;
        };
      };
      tags: {
        Row: {
          id: string;
          name: string;
          color: string;
          team_id: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          color: string;
          team_id: string;
          created_by: string;
          created_at?: string;
        };
        Update: {
          name?: string;
          color?: string;
        };
      };
      call_tags: {
        Row: {
          call_id: string;
          tag_id: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          call_id: string;
          tag_id: string;
          created_by: string;
          created_at?: string;
        };
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: {
      claim_team_invite: {
        Args: {
          p_user_id: string;
          p_code: string;
        };
        Returns: {
          team_id: string;
          uses: number;
          max_uses: number | null;
          current_reps: number;
          included_reps: number;
          overage_reps: number;
          estimated_monthly_cents: number;
        }[];
      };
    };
    Enums: {
      user_role: "rep" | "manager";
      call_status:
        | "uploading"
        | "uploaded"
        | "transcribing"
        | "transcribed"
        | "analyzing"
        | "completed"
        | "failed";
      speaker_type: "rep" | "customer" | "unknown";
      section_type:
        | "introduction"
        | "rapport_building"
        | "pitch"
        | "objection_handling"
        | "closing"
        | "other";
      objection_category:
        | "price"
        | "timing"
        | "need"
        | "trust"
        | "competition"
        | "authority"
        | "other";
      grade_type:
        | "excellent"
        | "good"
        | "acceptable"
        | "needs_improvement"
        | "poor";
    };
  };
}
